site:
  title: Valorem Protocol
  copyright: Valorem Labs Inc
  description: |
    Write permissionless physically settled options on any ERC20 token.
banner_markdown: |
  Open beta available now! Help shape the future of ERC20 options. [Launch app â†’](https://valorem-frontend.herokuapp.com/)
footer_markdown: |
  Valorem helps DeFi power users pursue advanced hedging strategies by writing their own physically settled options permissionlessly on any ERC20 token.
default_cta:
  heading: App coming soon. In the meantime, join our Discord server to get early beta access to our testnet release.
  buttons:
    - text: Join Discord
      url: https://discord.gg/jRNGhTef57